from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import AutoConfig
import torch
from dataclasses import dataclass
from token_utils import TokenUtils
from typing import Optional

@dataclass
class ModelResponse:
    """
    question: original question
    prompt: Question: {question}+{custom_instruction}+<think>
    cot: chain of thought
    answer: answer generated by the model
    """
    question_id: Optional[str]
    question: str
    prompt: str
    cot: str
    answer: str
    raw_output: str

    def __post_init__(self):
        self.basic_pair = (self.cot, self.answer)

    def old__str__(self):
        return f"""
ModelResponse(
    Question: {self.question},
    Prompt: {self._encode(self.prompt)}
    CoT: {self._encode(self.cot)}
    Answer: {self._encode(self.answer)}
)
"""

    def print(self):
        print(f"Question: {self._encode(self.question)}")
        print("\n")
        print(f"Prompt: {self._encode(self.prompt)}")
        print("\n")
        print("CoT: " + self._encode(self.cot))
        print("\n")
        print(f"Answer: {self._encode(self.answer)}")
        print("\n")


class Model:
    MODEL_CONFIG_QWEN = {
        "begin_think": "<think>",
        "end_think": "</think>",
    }

    MODEL_CONFIG_WLA = {
        "fuzzy_separator": "Answer: ",
    }

    SUPPORTED_MODELS = {
        "Qwen/Qwen3-0.6B": MODEL_CONFIG_QWEN,
        "Qwen/Qwen3-1.7B": MODEL_CONFIG_QWEN,
        "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B": MODEL_CONFIG_QWEN,
        #"deepcogito/cogito-v1-preview-llama-3B": MODEL_CONFIG_QWEN,  # unverified
        "Wladastic/Mini-Think-Base-1B": MODEL_CONFIG_WLA,
        "google/gemma-2-2b": MODEL_CONFIG_WLA,
        #"microsoft/phi-2": MODEL_CONFIG_WLA,  # not very consistent
    }

    def __init__(self, model_name: str, cache_dir="/tmp/cache"):
        if model_name not in self.SUPPORTED_MODELS:
            print(f"ERROR: model {model_name} is not in supported list {self.SUPPORTED_MODELS}")
            exit(1)

        self.model_name = model_name
        
        config = AutoConfig.from_pretrained(
            model_name,
            cache_dir=cache_dir,
            trust_remote_code=True,
        )

        try:
            self.tokenizer = AutoTokenizer.from_pretrained(
                model_name,
                cache_dir=cache_dir,
            )
            self.model = AutoModelForCausalLM.from_pretrained(
                model_name,
                config=config,
                torch_dtype=torch.float16,
                device_map="auto",
                cache_dir=cache_dir,
            )
            self.utils = TokenUtils(self.model, self.tokenizer)

        except Exception as e:
            print(f"Error loading model {model_name}: {e}")
            raise

    def generate_cot_response(self, question_id, question, max_new_tokens=4096):
        final_response = self.generate_cot_response_full(question_id, question, max_new_tokens)
        return final_response.basic_pair

    def make_prompt(self, question_id, question, custom_instruction="Let's think step by step."):
        model_config = self.SUPPORTED_MODELS[self.model_name]
        history = [
            {"role": "user", "content": f"Question: {question}\n{custom_instruction}"},
        ]
        continue_final_message = True

        if("begin_think" in model_config):
            history.append({"role": "assistant", "content": "<think>"})

            prompt = self.tokenizer.apply_chat_template(history,
                tokenize=False,
                add_generation_prompt=not continue_final_message,
                continue_final_message=continue_final_message)
        elif("fuzzy_separator" in model_config):
            continue_final_message = False
            self.tokenizer.chat_template
            return history[0]["content"]
        else:
            print(f"ERROR: model {self.model_name} missing CoT separator config")
            exit(1)

        return prompt

    def do_generate(self, question_id, prompt, max_new_tokens=4096):
        """Generate a response using Chain-of-Thought (CoT) prompting."""
        model_config = self.SUPPORTED_MODELS[self.model_name]

        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)
        output = self.model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.6,
            top_k=20,
            min_p=0.0,
            top_p=0.95,
            eos_token_id=self.tokenizer.eos_token_id,
            pad_token_id=self.tokenizer.eos_token_id,
            output_scores=True,
            return_dict_in_generate=True,
        )
        return output

    def get_log_probs(self, sequences: torch.Tensor):
        with torch.no_grad():
            outputs = self.model(input_ids=sequences)
            log_probs = torch.nn.functional.log_softmax(outputs.logits, dim=-1)
        return log_probs

    def do_split(self, sequences):
        model_config = self.SUPPORTED_MODELS[self.model_name]

        # should split the output into three parts: question, the chain of thought and the answer
        if("begin_think" in model_config):
            # Split before decoding
            begin_think = self._get_token_id(model_config["begin_think"])
            if(sequences[0][0] == begin_think):
                sequences[0] = sequences[0][1:]
            end_think = self._get_token_id(model_config["end_think"])
            # split to 3 pieces: piece 0: question; piece 1: cot; piece 2: answer
            pieces = self._split_on_tokens(sequences[0].tolist(), [begin_think, end_think])

            if len(pieces) < 3:
                full = self.tokenizer.decode(sequences[0], skip_special_tokens=True)
                raise RuntimeError(
                    f"Failed to extract CoT (too few pieces) from: {full}"
                )

            response0 = self.tokenizer.decode(pieces[0], skip_special_tokens=True)
            response1 = self.tokenizer.decode(pieces[1], skip_special_tokens=True)
            response2 = self.tokenizer.decode(pieces[2], skip_special_tokens=True)

            question = response0.strip()
            #cot = response0[len(prompt):].strip()
            cot = response1.strip()
            answer = response2.strip()

        elif("fuzzy_separator" in model_config):
            if(model_config["fuzzy_separator"] in sequences):
                pieces = sequences.split(model_config["fuzzy_separator"])
            else:
                print(f"ERROR: model {self.model_name} did not generate chain of thought separator {model_config['fuzzy_separator']}")
                # print(f"Response: {full_response}")
                exit(1)

            full = self.tokenizer.decode(sequences[0], skip_special_tokens=True)
            prompt_end = "Let's think step by step."
            s1 = full.split(prompt_end)
            s2 = s1[1].split(model_config["fuzzy_separator"])

            question = s1[0] + prompt_end
            cot = s2[0]
            answer = s2[1]

            print(f"Q={question}, C={cot}, A={answer}")
        else:
            raise RuntimeError(f"Model {self.model_name} missing CoT separator config")


        return (question, cot, answer)

    def generate_cot_response_full(self, question_id, question, max_new_tokens=4096):
        """Generate a response using Chain-of-Thought (CoT) prompting."""
        prompt = self.make_prompt(question_id, question)
        output = self.do_generate(question_id, prompt, max_new_tokens)
        sequences = output.sequences

        raw_output = self.tokenizer.decode(sequences[0], skip_special_tokens=True)

        (question, cot, answer) = self.do_split(sequences)

        return ModelResponse(
            question_id=question_id,
            question=question,
            prompt=prompt,
            cot=cot,
            answer=answer,
            raw_output=raw_output)

    def evaluate_cot_response(self, question_id, prompt, max_new_tokens=4096):
        """Generate a response using Chain-of-Thought (CoT) prompting."""
        prompt_tokens = self.utils.encode_to_tensor(prompt)
        return self.evaluate_cot_response_from_tokens(question_id, prompt_tokens, max_new_tokens)

    def evaluate_cot_response_from_tokens(self, question_id, prompt_tokens: torch.Tensor, max_new_tokens=4096):
        log_probs = self.get_log_probs(prompt_tokens)

        raw_output = self.tokenizer.decode(prompt_tokens, skip_special_tokens=True)

        (question, cot, answer) = self.do_split(log_probs, raw_output, prompt_tokens)

        return ModelResponse(
            question_id=question_id,
            question=question,
            prompt=prompt_tokens,
            cot=cot,
            answer=answer,
            raw_output=raw_output)

    def _split_on_tokens(self, lst, token_list):
        """Split a list into sublists, using 'token' as the delimiter (token is not included in results)."""
        result = []
        current = []
        for item in lst:
            if item in token_list:
                result.append(current)
                current = []
            else:
                current.append(item)
        result.append(current)
        return result

    def _get_token_id(self, token):
        token_id = self.tokenizer.convert_tokens_to_ids(token)
        if(token_id is None):
            print(f"ERROR: model {self.model_name} does not support {token} token")
            exit(1)
        return token_id

    def get_think_tokens(self):
        model_config = self.SUPPORTED_MODELS[self.model_name]

        begin_think = self._get_token_id(model_config["begin_think"])
        end_think = self._get_token_id(model_config["end_think"])
        return (begin_think, end_think)

if __name__ == "__main__":
    question = "A car travels 60 miles in 1.5 hours. What is its average speed?"
    print("Prompt: " + question.encode('unicode_escape').decode())

    model = Model("deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B", cache_dir="/tmp/cache2")
    (cot, answer) = model.generate_cot_response(0, question)
    print("\n")
    print("CoT: " + cot.encode('unicode_escape').decode())
    print("\n")
    print("Answer: " + answer.encode('unicode_escape').decode())
    print("\n")
    print("Evaluate replacing CoT with thinking TOKENS:")
    print("\n")
    model.evaluate_with_custom_cot_tokens(question,
        model.tokenizer.encode(cot, return_tensors="pt").to(model.model.device).squeeze(0))

